// src/pages/profile/profile.vue
<script setup>
import { ref, computed } from 'vue'

// 用户信息
const userInfo = ref({
  avatar: '/static/avatar/default.png',
  nickname: '乡音守护者',
  id: 'XY2024001',
  bio: '记录家乡的声音，传承方言文化',
  region: '四川·成都'
})

// 统计数据
const stats = ref({
  works: 12,
  likes: 568,
  following: 89,
  followers: 156
})

// 菜单列表
const menuList = ref([
  { id: 'works', name: '我的作品', icon: '🎵', count: 12 },
  { id: 'cards', name: '我的宝藏卡', icon: '🎴', count: 8 },
  { id: 'favorites', name: '我的收藏', icon: '⭐', count: 45 },
  { id: 'achievements', name: '成就徽章', icon: '🏆', count: 6 }
])

// 打卡数据
const checkInDays = ref([1, 2, 3, 5, 6, 8, 9, 10, 12, 15, 16, 17, 18, 19, 20])
const currentMonth = ref(new Date().getMonth() + 1)
const currentYear = ref(new Date().getFullYear())

// 连续打卡天数
const streakDays = ref(5)

// 生成日历数据
const calendarDays = computed(() => {
  const days = []
  const daysInMonth = new Date(currentYear.value, currentMonth.value, 0).getDate()
  
  for (let i = 1; i <= daysInMonth; i++) {
    days.push({
      day: i,
      checked: checkInDays.value.includes(i),
      isToday: i === new Date().getDate()
    })
  }
  
  return days
})

// 编辑资料
const editProfile = () => {
  uni.showToast({
    title: '编辑资料',
    icon: 'none'
  })
}

// 菜单点击
const handleMenuClick = (menu) => {
  uni.showToast({
    title: `进入${menu.name}`,
    icon: 'none'
  })
}

// 打卡
const checkIn = () => {
  const today = new Date().getDate()
  if (!checkInDays.value.includes(today)) {
    checkInDays.value.push(today)
    streakDays.value++
    uni.showToast({
      title: '打卡成功！',
      icon: 'success'
    })
  } else {
    uni.showToast({
      title: '今日已打卡',
      icon: 'none'
    })
  }
}

// 设置
const goSettings = () => {
  uni.showToast({
    title: '设置页面',
    icon: 'none'
  })
}
</script>

<template>
  <view class="container">
    <!-- 用户信息卡片 -->
    <view class="user-card">
      <view class="user-header">
        <view class="avatar-section">
          <image class="avatar" :src="userInfo.avatar" mode="aspectFill"></image>
          <view class="avatar-badge">✓</view>
        </view>
        <view class="user-info">
          <text class="nickname">{{ userInfo.nickname }}</text>
          <text class="user-id">ID: {{ userInfo.id }}</text>
          <view class="region-tag">
            <text class="region-icon">📍</text>
            <text class="region-text">{{ userInfo.region }}</text>
          </view>
        </view>
        <view class="edit-btn" @click="editProfile">
          <text>编辑</text>
        </view>
      </view>
      <text class="user-bio">{{ userInfo.bio }}</text>
      
      <!-- 统计数据 -->
      <view class="stats-row">
        <view class="stat-item">
          <text class="stat-num">{{ stats.works }}</text>
          <text class="stat-label">作品</text>
        </view>
        <view class="stat-divider"></view>
        <view class="stat-item">
          <text class="stat-num">{{ stats.likes }}</text>
          <text class="stat-label">获赞</text>
        </view>
        <view class="stat-divider"></view>
        <view class="stat-item">
          <text class="stat-num">{{ stats.following }}</text>
          <text class="stat-label">关注</text>
        </view>
        <view class="stat-divider"></view>
        <view class="stat-item">
          <text class="stat-num">{{ stats.followers }}</text>
          <text class="stat-label">粉丝</text>
        </view>
      </view>
    </view>
    
    <!-- 打卡日历 -->
    <view class="calendar-section">
      <view class="calendar-header">
        <view class="calendar-title">
          <text class="title-text">每日打卡</text>
          <view class="streak-badge">
            <text class="fire-icon">🔥</text>
            <text class="streak-text">连续{{ streakDays }}天</text>
          </view>
        </view>
        <view class="checkin-btn" :class="{ checked: checkInDays.includes(new Date().getDate()) }" @click="checkIn">
          <text>{{ checkInDays.includes(new Date().getDate()) ? '已打卡' : '打卡' }}</text>
        </view>
      </view>
      <view class="calendar-grid">
        <view 
          v-for="day in calendarDays" 
          :key="day.day"
          class="calendar-day"
          :class="{ checked: day.checked, today: day.isToday }"
        >
          <text class="day-num">{{ day.day }}</text>
          <text v-if="day.checked" class="check-mark">✓</text>
        </view>
      </view>
    </view>
    
    <!-- 功能菜单 -->
    <view class="menu-section">
      <view 
        v-for="menu in menuList" 
        :key="menu.id"
        class="menu-item"
        @click="handleMenuClick(menu)"
      >
        <view class="menu-left">
          <text class="menu-icon">{{ menu.icon }}</text>
          <text class="menu-name">{{ menu.name }}</text>
        </view>
        <view class="menu-right">
          <text class="menu-count">{{ menu.count }}</text>
          <text class="menu-arrow">›</text>
        </view>
      </view>
    </view>
    
    <!-- 设置入口 -->
    <view class="settings-section" @click="goSettings">
      <view class="settings-left">
        <text class="settings-icon">⚙️</text>
        <text class="settings-name">设置</text>
      </view>
      <text class="settings-arrow">›</text>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.container {
  min-height: 100vh;
  background: linear-gradient(180deg, #F5F1E8 0%, #EDE8DC 100%);
  padding: 24rpx;
  padding-bottom: 140rpx;
}

.user-card {
  background: #FFFFFF;
  border-radius: 28rpx;
  padding: 32rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 4rpx 20rpx rgba(0, 0, 0, 0.06);
  
  .user-header {
    display: flex;
    align-items: center;
    margin-bottom: 20rpx;
    
    .avatar-section {
      position: relative;
      margin-right: 24rpx;
      
      .avatar {
        width: 120rpx;
        height: 120rpx;
        border-radius: 50%;
        border: 4rpx solid #F5F1E8;
      }
      
      .avatar-badge {
        position: absolute;
        bottom: 0;
        right: 0;
        width: 36rpx;
        height: 36rpx;
        background: #2D5016;
        border-radius: 50%;
        color: #FFFFFF;
        font-size: 20rpx;
        display: flex;
        align-items: center;
        justify-content: center;
        border: 2rpx solid #FFFFFF;
      }
    }
    
    .user-info {
      flex: 1;
      
      .nickname {
        font-size: 36rpx;
        font-weight: 600;
        color: #3E3E3E;
        display: block;
        margin-bottom: 8rpx;
      }
      
      .user-id {
        font-size: 22rpx;
        color: #9E9E9E;
        display: block;
        margin-bottom: 8rpx;
      }
      
      .region-tag {
        display: inline-flex;
        align-items: center;
        background: rgba(45, 80, 22, 0.1);
        padding: 4rpx 12rpx;
        border-radius: 20rpx;
        
        .region-icon {
          font-size: 18rpx;
          margin-right: 4rpx;
        }
        
        .region-text {
          font-size: 20rpx;
          color: #2D5016;
        }
      }
    }
    
    .edit-btn {
      padding: 8rpx 20rpx;
      background: #F5F5F5;
      border-radius: 24rpx;
      font-size: 22rpx;
      color: #666666;
    }
  }
  
  .user-bio {
    font-size: 24rpx;
    color: #666666;
    line-height: 1.5;
    display: block;
    margin-bottom: 24rpx;
    padding-bottom: 24rpx;
    border-bottom: 2rpx solid #F5F5F5;
  }
  
  .stats-row {
    display: flex;
    justify-content: space-around;
    align-items: center;
    
    .stat-item {
      display: flex;
      flex-direction: column;
      align-items: center;
      
      .stat-num {
        font-size: 36rpx;
        font-weight: 600;
        color: #3E3E3E;
        margin-bottom: 4rpx;
      }
      
      .stat-label {
        font-size: 22rpx;
        color: #9E9E9E;
      }
    }
    
    .stat-divider {
      width: 2rpx;
      height: 40rpx;
      background: #EEEEEE;
    }
  }
}

.calendar-section {
  background: #FFFFFF;
  border-radius: 28rpx;
  padding: 28rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 4rpx 20rpx rgba(0, 0, 0, 0.06);
  
  .calendar-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 24rpx;
    
    .calendar-title {
      display: flex;
      align-items: center;
      
      .title-text {
        font-size: 30rpx;
        font-weight: 600;
        color: #3E3E3E;
        margin-right: 16rpx;
      }
      
      .streak-badge {
        display: flex;
        align-items: center;
        background: linear-gradient(135deg, #FFF5E6 0%, #FFE4CC 100%);
        padding: 4rpx 12rpx;
        border-radius: 20rpx;
        
        .fire-icon {
          font-size: 20rpx;
          margin-right: 4rpx;
        }
        
        .streak-text {
          font-size: 20rpx;
          color: #E67E22;
        }
      }
    }
    
    .checkin-btn {
      padding: 10rpx 28rpx;
      background: linear-gradient(135deg, #E67E22 0%, #D35400 100%);
      border-radius: 28rpx;
      font-size: 24rpx;
      color: #FFFFFF;
      font-weight: 500;
      
      &.checked {
        background: #E0E0E0;
        color: #9E9E9E;
      }
    }
  }
  
  .calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    gap: 12rpx;
    
    .calendar-day {
      aspect-ratio: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      border-radius: 12rpx;
      background: #F8F8F8;
      position: relative;
      
      &.checked {
        background: linear-gradient(135deg, #2D5016 0%, #4A7C2A 100%);
        
        .day-num {
          color: #FFFFFF;
        }
      }
      
      &.today {
        border: 2rpx solid #E67E22;
      }
      
      .day-num {
        font-size: 22rpx;
        color: #3E3E3E;
      }
      
      .check-mark {
        position: absolute;
        bottom: 4rpx;
        font-size: 16rpx;
        color: #FFFFFF;
      }
    }
  }
}

.menu-section {
  background: #FFFFFF;
  border-radius: 28rpx;
  padding: 0 28rpx;
  margin-bottom: 24rpx;
  box-shadow: 0 4rpx 20rpx rgba(0, 0, 0, 0.06);
  
  .menu-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 28rpx 0;
    border-bottom: 2rpx solid #F5F5F5;
    
    &:last-child {
      border-bottom: none;
    }
    
    &:active {
      opacity: 0.7;
    }
    
    .menu-left {
      display: flex;
      align-items: center;
      
      .menu-icon {
        font-size: 36rpx;
        margin-right: 16rpx;
      }
      
      .menu-name {
        font-size: 28rpx;
        color: #3E3E3E;
      }
    }
    
    .menu-right {
      display: flex;
      align-items: center;
      
      .menu-count {
        font-size: 24rpx;
        color: #9E9E9E;
        margin-right: 8rpx;
      }
      
      .menu-arrow {
        font-size: 32rpx;
        color: #CCCCCC;
      }
    }
  }
}

.settings-section {
  background: #FFFFFF;
  border-radius: 28rpx;
  padding: 28rpx;
  display: flex;
  justify-content: space-between;
  align-items: center;
  box-shadow: 0 4rpx 20rpx rgba(0, 0, 0, 0.06);
  
  &:active {
    opacity: 0.7;
  }
  
  .settings-left {
    display: flex;
    align-items: center;
    
    .settings-icon {
      font-size: 36rpx;
      margin-right: 16rpx;
    }
    
    .settings-name {
      font-size: 28rpx;
      color: #3E3E3E;
    }
  }
  
  .settings-arrow {
    font-size: 32rpx;
    color: #CCCCCC;
  }
}
</style>

// src/pages/Profile.tsx
import { useEffect } from 'react'
import { Settings, Grid3X3, Bookmark, Award, ChevronRight, Flame, MapPin, CalendarDays, Sparkles, ThumbsUp, Trophy } from 'lucide-react'
import { useApp } from '../App'
import { getStreakEndingOnDay, isTodayChecked, loadCheckinRecords } from '../lib/checkin'

function getFirstDayOfMonth(year: number, month: number) {
  return new Date(year, month, 1).getDay()
}

const weekDays = ['日', '一', '二', '三', '四', '五', '六']

export default function Profile() {
  const { state, selectPost, navigate, setActiveTab, setUserListType, isLoggedIn, refreshCheckinState } = useApp()

  useEffect(() => {
    refreshCheckinState()
  }, [refreshCheckinState])

  const year = state.currentYear
  const month = state.currentMonth
  const daysInMonth = new Date(year, month + 1, 0).getDate()
  const firstDay = getFirstDayOfMonth(year, month)
  const today = state.today
  const records = loadCheckinRecords()
  const todayChecked = isTodayChecked(records)

  const userPosts = state.posts.filter((_, i) => i % 2 === 0)

  const menuItems = [
    { icon: Grid3X3, label: '我的作品', desc: `${userPosts.length} 个乡音视频`, color: '#2D5016', screen: 'myWorks' as const },
    { icon: Bookmark, label: '我的宝藏卡', desc: `${state.myCards.length} 张收藏卡片`, color: '#8B2635', screen: 'myCards' as const },
    { icon: Sparkles, label: '我的收藏', desc: `${state.favorites.length} 项收藏`, color: '#E67E22', screen: 'favorites' as const },
    { icon: Award, label: '成就徽章', desc: `${state.myBadges.length} 枚已获得`, color: '#2D5016', screen: 'myBadges' as const },
    { icon: Settings, label: '设置', desc: '账号与隐私', color: '#9E9E9E', screen: 'settings' as const },
  ]

  return (
    <div className="h-full overflow-y-auto no-scrollbar bg-[#F5F1E8]">
      {/* Profile Header */}
      <div className="px-4 pt-4 pb-5">
        <div className="flex items-center gap-4">
          <button
            className="relative transition-transform active:scale-95"
            onClick={() => navigate('avatarSettings')}
          >
            <img
              src={state.currentAvatar}
              alt="avatar"
              className="w-18 h-18 rounded-full object-cover border-3 border-white card-shadow"
              style={{ width: 72, height: 72 }}
            />
            <div className="absolute -bottom-1 -right-1 bg-[#2D5016] text-white text-[9px] px-1.5 py-0.5 rounded-full font-medium">
              Lv.5
            </div>
          </button>
          <div className="flex-1">
            <button className="text-left" onClick={() => navigate('avatarSettings')}>
              <h2 className="text-lg font-bold text-[#3E3E3E]">{state.userNickname}</h2>
            </button>
            <p className="text-xs text-[#9E9E9E] mt-0.5 flex items-center gap-1">
              <MapPin size={10} />
              {isLoggedIn ? `@${state.userHandle}` : '未登录 · 记录乡音，留住文化的根'}
            </p>
          </div>
          <button
            className="w-9 h-9 rounded-full bg-white card-shadow flex items-center justify-center transition-transform active:scale-90"
            onClick={() => navigate('settings')}
          >
            <Settings size={16} className="text-[#9E9E9E]" />
          </button>
        </div>

        {!isLoggedIn && (
          <button
            className="w-full mt-3 py-3 bg-[#2D5016]/10 rounded-2xl flex items-center justify-center gap-2 text-[#2D5016] text-sm transition-transform active:scale-[0.98]"
            onClick={() => navigate('login')}
          >
            登录 / 注册，同步打卡与资料
          </button>
        )}

        {/* Stats - ALL CLICKABLE */}
        <div className="flex items-center justify-around mt-4 py-3 bg-white rounded-2xl card-shadow">
          <button className="flex flex-col items-center transition-transform active:scale-95" onClick={() => navigate('myWorks')}>
            <span className="text-lg font-bold text-[#3E3E3E]">{state.posts.length}</span>
            <span className="text-[11px] text-[#9E9E9E]">作品</span>
          </button>
          <div className="w-px h-8 bg-[#E0D8C8]" />
          <button className="flex flex-col items-center transition-transform active:scale-95" onClick={() => { setUserListType('liked'); navigate('userList') }}>
            <span className="text-lg font-bold text-[#3E3E3E]">1.2k</span>
            <span className="text-[11px] text-[#9E9E9E]">获赞</span>
          </button>
          <div className="w-px h-8 bg-[#E0D8C8]" />
          <button className="flex flex-col items-center transition-transform active:scale-95" onClick={() => { setUserListType('following'); navigate('userList') }}>
            <span className="text-lg font-bold text-[#3E3E3E]">86</span>
            <span className="text-[11px] text-[#9E9E9E]">关注</span>
          </button>
          <div className="w-px h-8 bg-[#E0D8C8]" />
          <button className="flex flex-col items-center transition-transform active:scale-95" onClick={() => { setUserListType('followers'); navigate('userList') }}>
            <span className="text-lg font-bold text-[#3E3E3E]">234</span>
            <span className="text-[11px] text-[#9E9E9E]">粉丝</span>
          </button>
        </div>
      </div>

      {/* 今日打卡状态（多邻国风格） */}
      {!todayChecked && (
        <div className="px-4 mb-3">
          <button
            className="w-full flex items-center gap-3 bg-gradient-to-r from-[#FF9600]/15 to-[#FF4B4B]/10 border border-[#FF9600]/30 rounded-2xl px-4 py-3 text-left transition-transform active:scale-[0.98]"
            onClick={() => { setActiveTab('discover'); navigate('discover') }}
          >
            <div className="w-10 h-10 rounded-full bg-[#FF9600] flex items-center justify-center shrink-0">
              <Trophy size={20} className="text-white" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold text-[#3E3E3E]">今日还未打卡</p>
              <p className="text-[11px] text-[#9E9E9E]">去地图选地区，完成方言闯关即可打卡</p>
            </div>
            <ChevronRight size={16} className="text-[#FF9600]" />
          </button>
        </div>
      )}

      {/* Check-in Calendar - CLICKABLE */}
      <div className="px-4 mb-4">
        <button
          className="w-full bg-white rounded-2xl card-shadow p-4 text-left transition-transform active:scale-[0.98]"
          onClick={() => navigate('checkinDetail')}
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <CalendarDays size={18} className="text-[#2D5016]" />
              <h3 className="text-sm font-semibold text-[#3E3E3E]">每日打卡</h3>
            </div>
            <div className="flex items-center gap-2">
              <div className="flex items-center gap-1 bg-orange-50 px-2 py-0.5 rounded-full">
                <Flame size={12} className="text-[#E67E22]" />
                <span className="text-[11px] text-[#E67E22] font-medium">连续 {state.streakDays} 天</span>
              </div>
              <ChevronRight size={16} className="text-[#E0D8C8]" />
            </div>
          </div>

          <div className="text-center text-xs text-[#9E9E9E] mb-2">
            {year}年{month + 1}月
          </div>

          <div className="grid grid-cols-7 gap-1 mb-1">
            {weekDays.map(d => (
              <div key={d} className="text-center text-[10px] text-[#9E9E9E] py-1">{d}</div>
            ))}
          </div>

          <div className="grid grid-cols-7 gap-1">
            {Array.from({ length: firstDay }).map((_, i) => (
              <div key={`empty-${i}`} />
            ))}
            {state.checkinDays.slice(0, daysInMonth).map(d => {
              const isToday = d.day === today
              const streak = d.checked
                ? getStreakEndingOnDay(records, year, month, d.day)
                : 0
              return (
                <div
                  key={d.day}
                  className={`aspect-square flex flex-col items-center justify-center rounded-lg text-xs font-medium relative ${
                    isToday && d.checked
                      ? 'bg-[#58CC02] text-white'
                      : isToday
                      ? 'bg-[#FF9600]/15 text-[#FF9600] ring-1 ring-[#FF9600]'
                      : d.checked
                      ? 'bg-[#2D5016]/10 text-[#2D5016]'
                      : 'text-[#3E3E3E]'
                  }`}
                >
                  <span>{d.day}</span>
                  {d.checked && d.level && (
                    <span className="text-[6px] leading-none mt-0.5 opacity-70">Lv.{d.level}</span>
                  )}
                  {streak >= 3 && streak < 7 && <ThumbsUp size={8} className="absolute -top-0.5 -right-0.5 text-[#2D5016]" />}
                  {streak >= 7 && <Flame size={8} className="absolute -top-0.5 -right-0.5 text-[#E67E22]" />}
                </div>
              )
            })}
          </div>
        </button>
      </div>

      {/* My Works Preview */}
      <div className="px-4 mb-4">
        <button className="w-full flex items-center justify-between mb-2 text-left transition-transform active:scale-[0.98]" onClick={() => navigate('myWorks')}>
          <h3 className="text-sm font-semibold text-[#3E3E3E]">我的作品</h3>
          <span className="text-[11px] text-[#2D5016] flex items-center gap-0.5">全部 <ChevronRight size={12} /></span>
        </button>
        <div className="grid grid-cols-3 gap-2">
          {userPosts.map(post => (
            <button key={post.id} className="aspect-[3/4] rounded-xl overflow-hidden relative card-shadow transition-transform active:scale-95" onClick={() => selectPost(post.id)}>
              <img src={post.image} alt="" className="w-full h-full object-cover" />
              <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" />
              <div className="absolute bottom-1.5 left-1.5 right-1.5">
                <p className="text-white text-[10px] truncate drop-shadow">{post.region}</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Menu Items */}
      <div className="px-4 pb-6">
        <div className="bg-white rounded-2xl card-shadow overflow-hidden">
          {menuItems.map((item, i) => {
            const Icon = item.icon
            return (
              <button
                key={item.label}
                className={`w-full flex items-center gap-3 px-4 py-3.5 text-left transition-colors active:bg-[#F5F1E8] ${i < menuItems.length - 1 ? 'border-b border-[#F5F1E8]' : ''}`}
                onClick={() => navigate(item.screen)}
              >
                <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{ background: `${item.color}12` }}>
                  <Icon size={18} style={{ color: item.color }} strokeWidth={1.5} />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-[#3E3E3E]">{item.label}</p>
                  <p className="text-[11px] text-[#9E9E9E]">{item.desc}</p>
                </div>
                <ChevronRight size={16} className="text-[#E0D8C8]" />
              </button>
            )
          })}
        </div>
      </div>
    </div>
  )
}
